### ISSUE TITLE
predictions.map is not a function

### ISSUE THREAD

**Issue by mas1515** [cloud-annotations/javascript-sdk#2]
when i test my model 
i got this error 
error image 

https://pasteboard.co/Ja7088N.png

please help me

**Comment by bourdakos1** [comment]
I’m guessing predictions is undefined for some reason

**Comment by mas1515** [comment]
i find my path was not ok and it works .

my code is here 

[]( https://github.com/cloud-annotations/javascript-sdk/issues/3)
