### ISSUE TITLE
load  cloud-annotations script locally   

### ISSUE THREAD

**Issue by mas1515** [cloud-annotations/javascript-sdk#4]
Hello 
is it possible load   this script 

    <script src="https://cdn.jsdelivr.net/npm/@cloud-annotations/models"></script>
locally (offline)  without internet ???
beacause it needs tensorflow js and i'm not sure that it works offline 

if this is possible please explain what file need to download and how use all of them??

**Comment by bourdakos1** [comment]
Just copy and paste the contents of this link into a js file https://cdn.jsdelivr.net/npm/@cloud-annotations/models

And then change the script tag to point to the local file

**Comment by mas1515** [comment]
I worked a lot with tensorflow js
I just wanted to use the plugin
To get to the result faster.
thank you man
