### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by mas1515** [cloud-annotations/javascript-sdk#9]
Hello @bourdakos1 
i have two problem 
1-  when i annotate new object in my unlabeled images ,  cloud not save my draw and reset all image to undraw state 

2- when i click train button 
it gives red error status without any message

**Comment by bourdakos1** [comment]
can you send a screenshot?

**Comment by mas1515** [comment]
this is error

https://pasteboard.co/JlMaY72.png

WHAT IS PROBLEM
IT WORKED LAST WEEK

**Comment by bourdakos1** [comment]
can you click download model and see if there is a log file?

**Comment by mas1515** [comment]
i downloaad model

but it has 999 image
and 1 annotaion file
this link  
https://easyupload.io/jvviru


what is problem ??

**Comment by mas1515** [comment]
every unlabeled image reset 
when i labeled them 
and not saving in labeled group

**Comment by mas1515** [comment]
@bourdakos1 

hello again

what is solution for these problem???

please help.
i repeated
1-  error for train button in web

2-  it is not possible for draw box in new image .
do you want i send my user and pass and check it  ???

**Comment by bourdakos1** [comment]
It’s failing to train because nothing is labeled. I’m not sure why things aren’t labeling... what browser and version are you using?

**Comment by mas1515** [comment]
@bourdakos1 

i labeled 1350 image before this error 
please help me

**Comment by bourdakos1** [comment]
I'm not sure I understand? I thought you said you labeled images, but the labels are gone now?

**Comment by mas1515** [comment]
@bourdakos1 
let me explain better

i labeled 1350 image last week 
after that  i want  label 250 new image

But  i can't labele any new image in  cloud .

what is problem ?????

**Comment by bourdakos1** [comment]
i'm not sure sorry :( maybe try another browser? firefox works fine for me, but I'm using a different version than you

**Comment by mas1515** [comment]
i test with chrome

and brave 
and edge 

but cant label new image

may i send user and pass to you 
and check it ???

**Comment by bourdakos1** [comment]
Sure

**Comment by mas1515** [comment]
@bourdakos1 
i email user and pass to you 

please check it 
thnaks

**Comment by bourdakos1** [comment]
@mas1515 I fixed the issue, you should be able to train now :) Sorry it took so long!
